### ISSUE TITLE
粘贴到后微信公众号后公式变得很大

### ISSUE THREAD

**Issue by hanbaoan123** [mdnice/markdown-nice-docs#6]
![image](https://user-images.githubusercontent.com/32160782/76680961-753edb00-6628-11ea-807a-9d520a8f9824.png)

**Comment by LinFeng1997** [comment]
@hanbaoan123 能提供一下原文地址吗

**Comment by hanbaoan123** [comment]
> @hanbaoan123 能提供一下原文地址吗

我文章还没发出去，这个问题只有当后面加了公式tag（\tag{1}）才会出现，我是直接点击复制到公众号，然后在公众号直接粘贴，如果按照视频中的更改element值就不会出现问题

**Comment by views63** [comment]
> 
> 
> > @hanbaoan123 能提供一下原文地址吗
> 
> 我文章还没发出去，这个问题只有当后面加了公式tag（\tag{1}）才会出现，我是直接点击复制到公众号，然后在公众号直接粘贴，如果按照视频中的更改element值就不会出现问题

复制粘贴方式目前找不到方法解决

**Comment by guanpengchn** [comment]
@hanbaoan123 请使用浏览器插件https://docs.mdnice.com/#/beta
